### ISSUE TITLE
Unable to build with Swift 5.9

### ISSUE THREAD

**Issue by gsfreema** [val-lang/val#847]
Attempting to build with the following Swift version results in a build failure.

```
swift-driver version: 1.87.1 Apple Swift version 5.9 (swiftlang-5.9.0.128.2 clang-1500.0.40.1)
Target: x86_64-apple-macosx14.0
```

```
val/Sources/FrontEnd/TypeChecking/TypeChecker.swift:908:25: error: generic parameter 'T' shadows generic parameter from outer scope with the same name; this is an error in Swift 6
    func checkSatisfied<T: Decl>(callable requirement: T.ID, named requiredName: Name) {
```

This is caused by a generic method with a generic parameter name T containing nested generic functions that also use a generic parameter T. I can see that a new TypeChecker is in the works, but it appears that is also suffers from this same issue. Using a different generic parameter name for the nested functions should resolve the issue.

**Comment by kyouko-taiga** [comment]
Good to know for planning ahead!
Would it be possible to list all occurrences of this problem on `main`? I don't have Swift 5.9 yet.

**Comment by gsfreema** [comment]
I just merged main into #853 and made the necessary changes. I believe the only instances are listed and resolved in the file changes for that PR. I'm at least able to run the build and tests 😄 .

**Comment by kyouko-taiga** [comment]
Great, thanks a lot!
